set(LEVELS "${OUTPUT_DIR}/sequence_duplication_levels_R1.tsv")
set(SUMMARY "${OUTPUT_DIR}/sequence_duplication_summary_R1.tsv")
set(OVERREPRESENTED "${OUTPUT_DIR}/overrepresented_sequences_R1.tsv")
set(INCOMPLETE "${OUTPUT_DIR}/sequence_duplication_R1.incomplete")

foreach(path IN ITEMS "${LEVELS}" "${SUMMARY}" "${OVERREPRESENTED}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Missing duplication artifact: ${path}")
    endif()
endforeach()

if(EXISTS "${INCOMPLETE}")
    message(FATAL_ERROR "Completed run retained transaction marker: ${INCOMPLETE}")
endif()

file(READ "${LEVELS}" levels_content)
string(REGEX MATCHALL "\n" level_newlines "${levels_content}")
list(LENGTH level_newlines level_line_count)
if(NOT level_line_count EQUAL 17)
    message(FATAL_ERROR "Expected header and 16 duplication bins, got ${level_line_count} lines")
endif()
if(NOT levels_content MATCHES "^duplication_level\ttotal_sequences_percent\tdeduplicated_sequences_percent\n")
    message(FATAL_ERROR "Unexpected sequence duplication schema")
endif()
if(NOT levels_content MATCHES "\n1\t40\\.0000000000\t66\\.6666666667\n")
    message(FATAL_ERROR "Incorrect level-1 percentages")
endif()
if(NOT levels_content MATCHES "\n2\t20\\.0000000000\t16\\.6666666667\n")
    message(FATAL_ERROR "Incorrect level-2 percentages")
endif()
if(NOT levels_content MATCHES "\n4\t40\\.0000000000\t16\\.6666666667\n")
    message(FATAL_ERROR "Incorrect level-4 percentages")
endif()

file(READ "${SUMMARY}" summary_content)
if(NOT summary_content MATCHES "^source_kind\talgorithm\tsource_fastq\tprefix_length\ttotal_reads\tunique_sequences\tdeduplicated_remaining_percent\n")
    message(FATAL_ERROR "Unexpected duplication summary schema")
endif()
if(NOT summary_content MATCHES "\nnative_fastq\tneoqc-exact-prefix-v1\tsequence_duplication\\.fq\t50\t10\t6\t60\\.0000000000\n$")
    message(FATAL_ERROR "Incorrect duplication provenance or headline statistic")
endif()

file(READ "${OVERREPRESENTED}" overrepresented_content)
if(NOT overrepresented_content MATCHES "^sequence\tcount\tpercentage\tpossible_source\n")
    message(FATAL_ERROR "Unexpected overrepresented-sequence schema")
endif()
