#!/usr/bin/env bash

set -euo pipefail

OUT_DIR="tests/data"
mkdir -p "$OUT_DIR"

ADAPTER="AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"

echo "Generating adapter test datasets..."

########################################
# adapter_profile
########################################

cat > "${OUT_DIR}/adapter_profile_R1.fq" <<EOF
@READ_001/1
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA${ADAPTER}
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@READ_002/1
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC${ADAPTER}
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
EOF

cat > "${OUT_DIR}/adapter_profile_R2.fq" <<EOF
@READ_001/2
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT${ADAPTER}
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@READ_002/2
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG${ADAPTER}
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
EOF

########################################
# partial_adapter
########################################

cat > "${OUT_DIR}/partial_adapter_R1.fq" <<EOF
@READ_001/1
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA${ADAPTER}
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@READ_002/1
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
EOF

cat > "${OUT_DIR}/partial_adapter_R2.fq" <<EOF
@READ_001/2
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT${ADAPTER}
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@READ_002/2
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
EOF

echo "Generated:"
echo "  ${OUT_DIR}/adapter_profile_R1.fq"
echo "  ${OUT_DIR}/adapter_profile_R2.fq"
echo "  ${OUT_DIR}/partial_adapter_R1.fq"
echo "  ${OUT_DIR}/partial_adapter_R2.fq"