#!/usr/bin/env bash

set -e

OUT_DIR="tests/data/adapter_tests"
mkdir -p "$OUT_DIR"

# Возьми тот адаптер, который есть в adapters.h
ADAPTER="AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"

########################################
# 1. Без адаптеров
########################################

cat > "$OUT_DIR/no_adapter.fq" <<EOF
@READ1
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@READ2
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@READ3
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
EOF

########################################
# 2. 50% ридов содержат адаптер
########################################

cat > "$OUT_DIR/half_adapter.fq" <<EOF
@READ1
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA${ADAPTER}
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@READ2
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC${ADAPTER}
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@READ3
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@READ4
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
EOF

########################################
# 3. Все риды содержат адаптер
########################################

cat > "$OUT_DIR/full_adapter.fq" <<EOF
@READ1
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA${ADAPTER}
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@READ2
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC${ADAPTER}
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@READ3
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG${ADAPTER}
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
EOF

echo "Generated:"
echo "  $OUT_DIR/no_adapter.fq"
echo "  $OUT_DIR/half_adapter.fq"
echo "  $OUT_DIR/full_adapter.fq"